[package]
name = "index-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
